### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [jdclouddevelopers/terraform-provider-jdcloud-archived#16]
Hey Team, 👋 My name is Chris, I'm a member of the Partner team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the master branch at git commit `f1f4b11`.

- [ ] There are a number of files that must be added in order for the provider to function in the Terraform native ecosystem.  
	- [ ] The GNUmakefile is pretty standard across all Terraform providers, feel free to copy the [NULL provider makefile](https://github.com/terraform-providers/terraform-provider-tls/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=jdcloud
	- [ ]  There are four bash scripts in a scripts/ that are used in different processes of testing and release, these can all be copied from the [NULL provider](https://github.com/terraform-providers/terraform-provider-null/tree/master/scripts) 
	- [ ] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the nexted release should be tagged as “(Unreleased)” and will then be updated with a date by the release-bot. 
	- [ ] All providers in the terraform-providers/ GitHub org have a TravisCI check run on each PR that is opened. Can you please update your .travis.yaml file to make the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)

- [ ] All of the Terraform Providers use a [Mozilla Public License 2.0](https://github.com/terraform-providers/terraform-provider-null/blob/master/LICENSE), would you be able to update your Apache license to MPL2.0?
- [ ] You will need to build website documentation for reach resource and data source, these are all written in Markdown with a ruby layout file for the sidebar formatting.  Check out the [NULL provider](https://github.com/terraform-providers/terraform-provider-null) website docs for help. (I can also help with this if needed.)
- [ ] When building the provider, I ran into a number of compile errors.  We’ll have to get these cleaned up before moving forward with the testing. 
```
$ make test
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \
		xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 github.com/terraform-providers/terraform-provider-jdcloud github.com/terraform-providers/terraform-provider-jdcloud/jdcloud
?   	github.com/terraform-providers/terraform-provider-jdcloud	[no test files]
# github.com/terraform-providers/terraform-provider-jdcloud/jdcloud
jdcloud/resource_jdcloud_disk.go:203: Errorf call needs 2 args but has 3 args
jdcloud/resource_jdcloud_instance.go:250: Printf call has arguments but no formatting directives
jdcloud/resource_jdcloud_instance.go:340: Errorf format %s has arg resp.Error of wrong type github.com/terraform-providers/terraform-provider-jdcloud/vendor/github.com/jdcloud-api/jdcloud-sdk-go/core.ErrorResponse
jdcloud/resource_jdcloud_oss_bucket_upload.go:71: Errorf call has arguments but no formatting directives
jdcloud/resource_jdcloud_eip_test.go:62: Errorf call needs 2 args but has 3 args
jdcloud/resource_jdcloud_instance_test.go:133: Errorf format %s has arg resp.Error of wrong type github.com/terraform-providers/terraform-provider-jdcloud/vendor/github.com/jdcloud-api/jdcloud-sdk-go/core.ErrorResponse
jdcloud/resource_jdcloud_network_interface_test.go:79: Errorf format %s has arg responseOnNetworkInterface.Error of wrong type github.com/terraform-providers/terraform-provider-jdcloud/vendor/github.com/jdcloud-api/jdcloud-sdk-go/core.ErrorResponse
FAIL	github.com/terraform-providers/terraform-provider-jdcloud/jdcloud [build failed]
make: *** [test] Error 1
```

Please let me know if you have any questions about this feedback. 

Thanks,
Chris

**Comment by cgriggs01** [comment]
In addition to my feedback I'd like to include this list of Terraform Provider code expectations/conventions that has been defined by the Terraform engineering team. Let me know if you have any questions.

 - [ ] resource filename matches convention `resource_providername_resourcename.go`
 - [ ] data source filename matches convention `data_source_providername_resourcename.go`
 - [ ] we always let `d.Set()` to dereference pointers safely to avoid crashes, i.e. there's nothing like `d.Set(*variable)`
 - [ ] flatteners and expanders are in `structures.go` + tests in `structures_test.go`
 - [ ] any validation functions longer than a few lines are in `validators.go` + tests in `validators_test.go`
 - [ ] `d.Set()` is called in any C/R/U/D for all available fields unless they're Computed-only (i.e. there are no orphans)
 - [ ] all of `d.Set()`, `d.Get()`, `d.GetOk()`, `d.GetChange()` etc. use real field names (i.e. no typos)
 - [ ] `d.Set()` is _always_ error-checked if it’s set, list or map
 - [ ] `d.Set()` is _never_ error-checked if it's primitive data type (string, int, float, bool)
 - [ ] Resource uses either `Read` or `Exists` function to remove resource from state if it's gone
 - [ ] `d.Partial()` & `d.SetPartial()` are used any time there's more than 1 API call used to create or update a resource.
 - [ ] `schema.ForceNew` is used for any field that is not updatable
 - [ ] all field names are `lowercase_underscore`
 - [ ] where possible data source fields match resource (e.g. when referencing `aws_instance` user shouldn't need to change anything - just add `data.` prefix)
 - [ ] Constants are used if there are available in the upstream SDK (e.g. for status codes)
 - [ ] `[INFO]` log message at least 2 per each C/R/U/D - e.g. creating (input), created (output)
 - [ ] The provider code does not `panic`, always returns errors

**Comment by XiaohanLiang** [comment]
Hey @cgriggs01 ,

It’s been 24th/December, Merry Christmas and thank for all your great job and contributions to Terraform. Hope you can have a nice holiday.

After days of working with this plugin, we’ve fixed the problem you have mentioned in the github issues, which includes:

- [x] Updated the LISCENCE to MPL
- [x] Implemented the website related files
- [x] Updated `Makefile` -> `GNUMakefile`
- [x] Created several bash scripts for multiple purposes
- [x] Implemented `CHANGELOG.md` with some recent updates.
- [x] Fixed the bugs on make test
- [x] `.travis.yml` updated which integrated multiple go test in it. However `website-test` was temporarily removed since, I think it might need some modification to `hashicorp/middleman` to complete website-test.(e.g. add jdcloud to providers fileds)

We’ve also checked the format of our code as suggested:

- [x] conduct error-check when applying `d.Set` to `TypeList` and `TypeSet`
- [x] Use constants for digital numbers(e.g.status codes)
- [x] `d.Setpartial()` and `d.partial()` set when multiple API calls are made

If any more problem is found, please leave it and just let us know , we will solve these problem in the quickest way possible :-)

Regards,
Xiaohan Liang

**Comment by cgriggs01** [comment]
Hi Xiaohan,

Thanks for addressing all of the feedback.  I will run the acceptance test again and let you know. 

Best,
Chris

**Comment by cgriggs01** [comment]
When running the acceptance tests. We’re still running into a few failed tests. The first two, there seems to been an error when destroying the test resource cluster. The third failed test looks to be an error with provisioning in US_EAST_1, is there another region that this should be tested in?

```
=== RUN   TestAccMongodbatlasCluster_basic
--- FAIL: TestAccMongodbatlasCluster_basic (1187.13s)
    testing.go:599: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Check failed: Cluster "5c3792fc79358e2124a76e47" still exists

        State: <no state>
=== RUN   TestMongodbatlasCluster_importBasic
--- FAIL: TestMongodbatlasCluster_importBasic (511.79s)
    testing.go:599: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Check failed: Cluster "5c37979fc56c989c8c692778" still exists

        State: <no state>
=== RUN   TestAccMongodbatlasContainer_basic
--- FAIL: TestAccMongodbatlasContainer_basic (1.57s)
    testing.go:538: Step 0 error: Error applying: 1 error(s) occurred:

        * mongodbatlas_container.test: 1 error(s) occurred:

        * mongodbatlas_container.test: Error creating MongoDB Container: MongoDB Atlas: 409 Cannot modify in use containers. Resources already exist in US_EAST_1. Creating resources in US_EAST_1 is not supported..
```

The only other item is that the datasource for `container` and resources for `alert configuration` and `VPC peering` connection do not have corresponding tests. Do you plan to add these test files?


Although the items above should be address before provider official release, I’m going to move this provider into the queue to be review by one of our Terraform ecosystem engineers. You’ll be the 3rd integration in the queue so it will be a few weeks before an engineer is available to review. 

Let me know if you have any questions about those.

**Comment by cgriggs01** [comment]
Hey Team,

I’ve bee continuously hitting these same failed tests. Any thought on what would be causing this. 
```
--- FAIL: TestAccJDCloudDiskAttachment_basic (3.47s)
    testing.go:513: Step 0 error: Error applying: 1 error occurred:
        	* jdcloud_disk_attachment.disk-attachment-TEST-1: 1 error occurred:
        	* jdcloud_disk_attachment.disk-attachment-TEST-1: [ERROR] resourceJDCloudDiskAttachmentCreate  code:401 staus:ACCESS_ERROR message:sign result is not same [gw]

--- FAIL: TestAccJDCloudDisk_basic (6.90s)
    testing.go:513: Step 0 error: Error applying: 1 error occurred:
        	* jdcloud_disk.disk_test_1: 1 error occurred:
        	* jdcloud_disk.disk_test_1: [DEBUG] resourceJDCloudDiskCreate  code:401 staus:ACCESS_ERROR message:sign result is not same [gw]

    testing.go:573: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        Error: Check failed: [ERROR] testAccCheckDiskDestroy Failed subnetID is empty
        State: <no state>

--- FAIL: TestAccJDCloudEIPAssociation_basic (1.80s)
    testing.go:513: Step 0 error: Error applying: 1 error occurred:
        	* jdcloud_eip_association.eip-association-TEST-1: 1 error occurred:
        	* jdcloud_eip_association.eip-association-TEST-1: [ERROR] resourceAssociateElasticIpCreate code:401 staus:ACCESS_ERROR message:sign result is not same [gw]
```

On the last test there is a runtime panic at occurs. Do you have any thoughts on what is causing this issue? If you need more of the tests output, I can email it directly to you.

**Comment by XiaohanLiang** [comment]
@cgriggs01   

Hey Chris, the problem appears to be the access_key and secret_key and their privileges. 

I just sent you a new pair of keys with full control to resources.

Sorry that was my stupid but the similar mistake won't appear again :-P

**Comment by cgriggs01** [comment]
Hi Team, 

Thank you for your patience throughout the process. A Terraform engineer has just become available and will start to reviewing the provider next week. The technical review process should take 2-3 weeks depending on the amount of feedback provided by the reviewing engineer. 

I will close this issue now and a new issue will be created for the technical review.

Best,
Chris
